"""Add document processing with Textract support

Revision ID: 67179ad993a5
Revises: 9d72ba8c4ae3
Create Date: 2026-03-03 02:46:52.632567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67179ad993a5'
down_revision: Union[str, None] = '9d72ba8c4ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    document_status = postgresql.ENUM('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentstatus')
    document_status.create(op.get_bind(), checkfirst=True)
    
    op.add_column('documents', sa.Column('s3_key', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentstatus'), nullable=False))
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('extraction_confidence', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.drop_column('documents', 's3_path')
    op.drop_column('documents', 'uploaded_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('s3_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'extraction_confidence')
    op.drop_column('documents', 'extracted_text')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 's3_key')
    
    # Drop enum type
    document_status = postgresql.ENUM('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentstatus')
    document_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
